# Generated by Django 5.2 on 2025-05-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='banios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cantidad_inquilinos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='habitaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='pisos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='politica_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='posee_cochera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tiene_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('local', 'Local'), ('otro', 'Otro')], default='Casa', max_length=50),
        ),
    ]
