# Generated by Django 5.2 on 2025-05-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_inmueble_banios_inmueble_cantidad_inquilinos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cochera',
            fields=[
                ('inmueble_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_inmuebles.inmueble')),
                ('tipo_cochera', models.CharField(choices=[('Cubierta', 'Cubierta'), ('Descubierta', 'Descubierta')], default='-')),
            ],
            bases=('gestion_inmuebles.inmueble',),
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='tiene_internet',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='precio',
            new_name='Precio',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='banios',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='cantidad_inquilinos',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='habitaciones',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='pisos',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='posee_cochera',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='Tiempo',
            field=models.CharField(choices=[('Por_hora', 'Por hora'), ('Por_dia', 'Por día'), ('Por_semana', 'Por semana'), ('Por_mes', 'Por mes'), ('Por_noche', 'Por noche')], default='-'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No_disponible', 'No disponible'), ('Mantenimiento', 'En mantenimiento')], default='Disponible'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Local', 'Local'), ('Otro', 'Otro')], default='Casa'),
        ),
        migrations.CreateModel(
            name='InmueblesSimilares',
            fields=[
                ('inmueble_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_inmuebles.inmueble')),
                ('tiene_internet', models.BooleanField(default=False)),
                ('baños', models.IntegerField(default=0)),
                ('tiene_cochera', models.BooleanField(default=False)),
                ('superficie', models.IntegerField(default=0)),
            ],
            bases=('gestion_inmuebles.inmueble',),
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('inmueblessimilares_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_inmuebles.inmueblessimilares')),
                ('pisos', models.IntegerField(blank=True, null=True)),
                ('cantidad_inquilinos', models.IntegerField(default=1)),
            ],
            bases=('gestion_inmuebles.inmueblessimilares',),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('inmueblessimilares_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_inmuebles.inmueblessimilares')),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('cantidad_inquilinos', models.IntegerField(default=1)),
            ],
            bases=('gestion_inmuebles.inmueblessimilares',),
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('inmueblessimilares_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_inmuebles.inmueblessimilares')),
                ('frente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fondo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('gestion_inmuebles.inmueblessimilares',),
        ),
    ]
