# Generated by Django 5.2 on 2025-05-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0003_cochera_remove_inmueble_tiene_internet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueblessimilares',
            name='superficie',
        ),
        migrations.AddField(
            model_name='cochera',
            name='ancho_plaza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cochera',
            name='largo_plaza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cochera',
            name='plazas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='superficie',
            field=models.IntegerField(default=0),
        ),
    ]
