# Generated by Django 5.2 on 2025-05-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0004_remove_inmueblessimilares_superficie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='calle',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ciudad',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='numero',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='provincia',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
