# Generated by Django 5.2 on 2025-05-17 15:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0005_remove_inmueble_direccion_remove_inmueble_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='Tiempo',
            new_name='tiempo',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(default='-', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='casa',
            name='cantidad_inquilinos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='casa',
            name='pisos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='ancho_plaza',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='largo_plaza',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='plazas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cantidad_inquilinos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='piso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='calle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='superficie',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueblessimilares',
            name='baños',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='local',
            name='fondo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='local',
            name='frente',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
