# Generated by Django 5.2 on 2025-05-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0007_rename_baños_inmueblessimilares_banios'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inmueblessimilares',
            name='habitaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
