# Generated by Django 5.2 on 2025-06-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0009_alter_inmueble_calle_alter_inmueble_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cochera',
            name='ancho_plaza',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='largo_plaza',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='local',
            name='fondo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='local',
            name='frente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
