# Generated by Django 5.2 on 2025-06-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0010_alter_cochera_ancho_plaza_alter_cochera_largo_plaza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tiempo',
        ),
    ]
