# Generated by Django 5.2 on 2025-05-19 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_inmuebles', '0004_remove_inmueblessimilares_superficie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('cochera', 'Cochera')], max_length=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('datos_inquilinos', models.JSONField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
