# Generated by Django 5.2.1 on 2025-05-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(default='efectivo', max_length=50),
        ),
    ]
