# Generated by Django 5.2 on 2025-05-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tipo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta de crédito/débito')], default='efectivo', max_length=20),
        ),
    ]
