# Generated by Django 5.2.1 on 2025-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0002_remove_reserva_tipo_reserva_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
    ]
