# Generated by Django 5.2 on 2025-05-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0003_alter_reserva_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta de crédito/débito')], default='efectivo', max_length=20),
        ),
    ]
