# Generated by Django 5.2.1 on 2025-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0004_alter_reserva_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('titular', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=4)),
                ('monto_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_pago', 'Pendiente de pago'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito')], default='efectivo', max_length=20),
        ),
    ]
