# Generated by Django 5.2.1 on 2025-05-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0005_tarjeta_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='monto_disponible',
        ),
    ]
