# Generated by Django 5.2.1 on 2025-05-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0006_remove_tarjeta_monto_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='monto_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
