# Generated by Django 5.2.1 on 2025-06-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reserva', '0007_tarjeta_monto_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_pendiente_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
